# Generated by Django 5.2.4 on 2025-10-16 08:15

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
