# Generated by Django 5.2 on 2025-06-30 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('cardiology', 'Cardiology'), ('pediatrics', 'Pediatrics'), ('orthopedics', 'Orthopedics'), ('neurology', 'Neurology'), ('gynecology', 'Gynecology')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
    ]
